apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config 
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "nginx -s reload || true"]
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config
